### ISSUE TITLE
Are executables mandatory?

### ISSUE THREAD

**Issue by FiratUsta** [LaurieWired/Halloween_2024_Programming_Challenge#2]
I am writing my CAPTCHA implementation in JS. GitHub pages works as a demo of it just fine.

I could wrap the whole page in an Electron app but why would I do that to you or anyone else.

If an executable is mandatory, I will provide it with electron, if not, I'll just submit the repo with a page enabled.

Thank you very much in advance for the response.

**Comment by olokelo** [comment]
According to Laurie's comments on her Youtube Short you don't need to provide a binary as long as you provide precise instructions on how to run your script. I suppose if you host it on Github Pages it will be even better.

**Comment by FiratUsta** [comment]
Thank you!

**Comment by LaurieWired** [comment]
Yup!  Github pages is just fine :)

**Comment by FiratUsta** [comment]
Thanks! I think I submitted? Hopefully I did lol
